server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    # --- ROUTES API (Laravel) ---
    location /api {
        try_files $uri /backend/public/index.php?$query_string;
    }

    # --- ROUTES FRONT-END (React ou autre) ---
    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- PHP / Laravel ---
    location ~ \.php$ {
        fastcgi_pass electro_laravel:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

