services:
  - type: web
    name: h-electro
    env: php
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT


