<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->truncate();

        DB::table('products')->insert([
            [
                'category_id' => 3,
                'name' => 'Boite-à-bijoux',
                'slug' => 'Boite-à-bijoux',
                'description' => 'Boîte élégante pour ranger bijoux et accessoires.',
                'price' => 6000,
                'stock_quantity' => 15,
                'is_published' => 1,
                'main_image_url' => '/images/products/Boite-à-bijoux.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'cadre-photo',
                'slug' => 'cadre-photo',
                'description' => 'Cadre photo moderne.',
                'price' => 4000,
                'stock_quantity' => 22,
                'is_published' => 1,
                'main_image_url' => '/images/products/cadre-photo.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'coque-iphone-15-pro',
                'slug' => 'coque-iphone-15-pro',
                'description' => 'Coque personnalisée pour iPhone 15 Pro.',
                'price' => 8000,
                'stock_quantity' => 30,
                'is_published' => 1,
                'main_image_url' => '/images/products/coque-iphone-15-pro.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'deco-noel',
                'slug' => 'deco-noel',
                'description' => 'Décoration de Noël personnalisée.',
                'price' => 3000,
                'stock_quantity' => 100,
                'is_published' => 1,
                'main_image_url' => '/images/products/deco-noel.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'mug-blanc',
                'slug' => 'mug-blanc',
                'description' => 'Mug blanc personnalisable.',
                'price' => 3500,
                'stock_quantity' => 40,
                'is_published' => 1,
                'main_image_url' => '/images/products/mug-blanc.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'mug-noir',
                'slug' => 'mug-noir',
                'description' => 'Mug noir personnalisable.',
                'price' => 5000,
                'stock_quantity' => 20,
                'is_published' => 1,
                'main_image_url' => '/images/products/mug-noir.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'outils-bureau',
                'slug' => 'outils-bureau',
                'description' => 'Outils de bureau personnalisés.',
                'price' => 6000,
                'stock_quantity' => 50,
                'is_published' => 1,
                'main_image_url' => '/images/products/outils-bureau.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'puzzle',
                'slug' => 'puzzle',
                'description' => 'Puzzle personnalisé.',
                'price' => 4500,
                'stock_quantity' => 80,
                'is_published' => 1,
                'main_image_url' => '/images/products/puzzle.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'sapin-noel',
                'slug' => 'sapin-noel',
                'description' => 'Sapin de Noël décoratif personnalisé.',
                'price' => 4500,
                'stock_quantity' => 40,
                'is_published' => 1,
                'main_image_url' => '/images/products/sapin-noel.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'sticker-vinyle-rectangle.avif',
                'slug' => 'sticker-vinyle-rectangle',
                'description' => 'Sticker vinyle rectangle.',
                'price' => 800,
                'stock_quantity' => 100,
                'is_published' => 1,
                'main_image_url' => '/images/products/sticker-vinyle-rectangle.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'sticker-vinyle-rond',
                'slug' => 'sticker-vinyle-rond',
                'description' => 'Sticker vinyle rond.',
                'price' => 800,
                'stock_quantity' => 100,
                'is_published' => 1,
                'main_image_url' => '/images/products/sticker-vinyle-rond.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'trophee',
                'slug' => 'trophee',
                'description' => 'Trophée en plexiglass.',
                'price' => 12000,
                'stock_quantity' => 20,
                'is_published' => 1,
                'main_image_url' => '/images/products/trophee.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'vase',
                'slug' => 'vase',
                'description' => 'Vase décoratif.',
                'price' => 9000,
                'stock_quantity' => 25,
                'is_published' => 1,
                'main_image_url' => '/images/products/vase.avif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
